# Generated by Django 3.2.9 on 2021-11-24 15:05

from django.db import migrations, models
import django.db.models.deletion
import spaceflights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20, verbose_name='компания-владелец')),
                ('name', models.CharField(max_length=20, verbose_name='название корабля')),
                ('flight_price', models.PositiveIntegerField(verbose_name='цена полета')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='вместимость')),
                ('image', models.ImageField(upload_to=spaceflights.models.get_upload_path, verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'корабли',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=10, verbose_name='пассажир')),
                ('flight_date', models.DateField(verbose_name='дата полета')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceflights.spaceship', verbose_name='корабль')),
            ],
        ),
    ]
